### ISSUE TITLE
你好，我想把这个实现用在我的demo中，是否可以呢？

### ISSUE THREAD

**Issue by yytsweet** [HJCYFY/ECO#1]
你好，我看到你的这个实现，想用到我的demo中，是否可以呢？
因为没有看到License，想咨询一下许可。

**Comment by NewboySoCool** [comment]
> 你好，我看到你的这个实现，想用到我的demo中，是否可以呢？ 因为没有看到License，想咨询一下许可。

能跑通吗？ 这个代码
